VehicleCostsMonitor.Web/Areas/Admin/Controllers/ManufacturerController.cs
namespace VehicleCostsMonitor.Web.Areas.Admin.Controllers
{
    using Common.Notifications;
    using Infrastructure.Filters;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using Services.Models.Manufacturer;
    using System.Threading.Tasks;

    public class ManufacturerController : BaseAdminController
    {
        private readonly IManufacturerService manufacturers;

        public ManufacturerController(IManufacturerService manufacturers)
        {
            this.manufacturers = manufacturers;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await this.manufacturers.AllAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var model = await this.manufacturers.GetDetailedAsync(id);
            if (model == null)
            {
                this.ShowNotification(string.Format(NotificationMessages.ManufacturerDoesNotExist, id));
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            var newManufacturerId = await this.manufacturers.CreateAsync(name);
            if (newManufacturerId == default(int))
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
            }
            else
            {
                this.ShowNotification(string.Format(
                    NotificationMessages.ManufacturerCreatedSuccessfull, name),
                    NotificationType.Success);
            }

            return RedirectToAction(nameof(this.Details), new { id = newManufacturerId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.manufacturers.GetForUpdateAsync(id);
            if (model == null)
            {
                this.ShowNotification(string.Format(NotificationMessages.ManufacturerDoesNotExist, id));
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> Edit(ManufacturerUpdateServiceModel model)
        {
            var success = await this.manufacturers.UpdateAsync(model.Id, model.Name);
            if (!success)
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
            }
            else
            {
                this.ShowNotification(string.Format(
                    NotificationMessages.ManufacturerUpdatedSuccessfull, model.Name),
                    NotificationType.Success);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await this.manufacturers.GetForUpdateAsync(id);
            if (model == null)
            {
                this.ShowNotification(string.Format(NotificationMessages.ManufacturerDoesNotExist, id));
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> Delete(ManufacturerUpdateServiceModel model)
        {
            var success = await this.manufacturers.DeleteAsync(model.Id);
            if (!success)
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
            }
            else
            {
                this.ShowNotification(string.Format(
                    NotificationMessages.ManufacturerDeletedSuccessfull, model.Name),
                    NotificationType.Success);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

VehicleCostsMonitor.Web/Areas/Admin/Controllers/VehicleModelController.cs
namespace VehicleCostsMonitor.Web.Areas.Admin.Controllers
{
    using Infrastructure.Filters;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using Services.Models.Vehicle;
    using System.Threading.Tasks;
    using VehicleCostsMonitor.Common.Notifications;

    public class VehicleModelController : BaseAdminController
    {
        private readonly IVehicleModelService vehicleModels;

        public VehicleModelController(IVehicleModelService vehicleModels)
        {
            this.vehicleModels = vehicleModels;
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name, int manufacturerId)
        {
            var success = await this.vehicleModels.CreateAsync(name, manufacturerId);
            if (!success)
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
            }
            else
            {
                this.ShowNotification(
                    string.Format(NotificationMessages.ModelCreatedSuccessfull, name),
                    NotificationType.Success);
            }

            return RedirectToAction(nameof(ManufacturerController.Details), "Manufacturer", new { id = manufacturerId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.vehicleModels.GetAsync(id);
            if (model == null)
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
                return RedirectToAction(nameof(ManufacturerController.Index), "Manufacturer");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> Edit(ModelConciseServiceModel model)
        {
            bool success = await this.vehicleModels.UpdateAsync(model.Id, model.Name);
            if (!success)
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
            }
            else
            {
                this.ShowNotification(string.Format(NotificationMessages.ModelUpdatedSuccessfull, model.Name), NotificationType.Success);
            }

            return RedirectToAction(nameof(ManufacturerController.Details), "manufacturer", new { id = model.ManufacturerId });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await this.vehicleModels.GetAsync(id);
            if (model == null)
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
                return RedirectToAction(nameof(ManufacturerController.Index), "Manufacturer");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateModelState]
        public async Task<IActionResult> Delete(ModelConciseServiceModel model)
        {
            var success = await this.vehicleModels.DeleteAsync(model.Id);
            if (success)
            {
                this.ShowNotification(
                    string.Format(NotificationMessages.ModelDeletedSuccessfull, model.Name),
                    NotificationType.Success);
            }
            else
            {
                this.ShowNotification(NotificationMessages.InvalidOperation);
            }

            return RedirectToAction(nameof(ManufacturerController.Details), "Manufacturer", new { id = model.ManufacturerId });
        }
    }
}

VehicleCostsMonitor.Web/Areas/Admin/Views/Manufacturer/Delete.cshtml
@model ManufacturerUpdateServiceModel

<h2>Delete @Model.Name</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="text" name="name" value="@Model.Name" hidden="hidden" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-default">Back to List</a>
    </form>
</div>

VehicleCostsMonitor.Web/Areas/Admin/Views/Manufacturer/Details.cshtml
@model ManufacturerDetailsServiceModel

<h2 class=" text-center">Details for @Model.Name</h2>

<div>
    <hr />
    <div class="container">
        <div class="col-md-4"></div>
        <div class="col-md-4 form-inline">
            <form asp-controller="VehicleModel" asp-action="Create" method="post">
                <input type="text" hidden="hidden" name="manufacturerId" value="@Model.Id" />
                <input class="form-control" name="name" type="text" placeholder="Add new model" />
                <input type="submit" value="Create new" class="btn btn-primary" />
            </form>
        </div>
    </div>
    <div class="container">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            Manufacturer
                        </th>
                        <th>
                            Model
                        </th>
                        <th>
                            Id
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var vehicleModel in Model.Models)
                    {
                        <tr>
                            <td>@Model.Name</td>
                            <td>@vehicleModel.Name</td>
                            <td>@vehicleModel.Id</td>
                            <td>
                                <a asp-area="admin" asp-controller="vehiclemodel" asp-action="edit" asp-route-id="@vehicleModel.Id" class="btn btn-warning">Edit</a>
                                <a asp-area="admin" asp-controller="vehiclemodel" asp-action="delete" asp-route-id="@vehicleModel.Id" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-default">Back to List</a>
</div>

VehicleCostsMonitor.Web/Areas/Admin/Views/Manufacturer/Edit.cshtml
@model ManufacturerUpdateServiceModel

<h2>Edit "@Model.Name"</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input readonly="readonly" asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-default" asp-action="Index">Back to List</a>
</div>

VehicleCostsMonitor.Web/Areas/Admin/Views/Manufacturer/Index.cshtml
@model IEnumerable<ManufacturerConciseListModel>

<h2 class="text-center">All manufacturers</h2>
<hr />
<div class="container body-content">
    <div class="container">
        <div class="col-md-4"></div>
        <div class="col-md-4 form-inline">
            <form asp-action="create" method="post">
                <input class="form-control" name="name" type="text" placeholder="Add new manufacturer" />
                <input type="submit" value="Create new" class="btn btn-primary" />
            </form>
        </div>
    </div>
    <br />
    <div class="container">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th width="30%">
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th width="30%">
                            @Html.DisplayNameFor(model => model.ModelsCount)
                        </th>
                        <th width="40%">
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ModelsCount)
                            </td>
                            <td>
                                <a class="btn btn-primary" asp-action="details" asp-route-id="@item.Id">Details</a>
                                <a class="btn btn-warning" asp-action="edit" asp-route-id="@item.Id">Edit</a>
                                <a class="btn btn-danger" asp-action="delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>